---
output: 
  pdf_document:
    citation_package: natbib
    keep_tex: true
    fig_caption: true
    latex_engine: pdflatex
    template: ./svm-latex-ms.tex
title: "What Should Central Bankers Do?"
author:
- name: Kaiden Billings
  affiliation: Utah State University
abstract: "Buchanan's approach what economists should do is used as a model to analyze what central banks should do. An anlysis is given of inflation targeting and nominal GDP targeting approaches to monetary policy. Central banks can leverage information markets to influence monetary policy decisions, but it may be difficult for monetary tools to effectively influence GDP."
keywords: "central banks, federal reserve, nominal GDP targeting"
date: "`r format(Sys.time(), '%B %d, %Y')`"
geometry: margin=1in
fontfamily: mathpazo
fontsize: 11pt
spacing: double
bibliography: master.bib
biblio-style: apsr
---


>  

The Federal Reserve may be the most powerful financial institution in the world. It has supervisory power over many of the world’s largest banks and the ability to directly influence the money supply of the largest economy in the world. This influence spreads to markets and economies around the world. Due to this profound influence on the world economy, there is constant debate on the role of the Federal Reserve and how monetary policy is conducted. As James Buchanan wrote, “improvement must, therefore, be sought in reforms in process, in institutional change that will allow the operations of politics to mirror more accurately that set of results that are preferred by those who participate… the constitution of policy rather than policy itself becomes the relevant object for reform (Buchanan 1987).” This paper will reflect this approach to analyzing the processes that lead to monetary policy decisions and contribute to the question of what central bankers should do. 

#The Information Problem

The Federal Reserve relies on statistical aggregates of data and macroeconomic models to inform their policy decisions. There is an inherent information problem with monetary policy. There is no way 12 people, or 1,200 people, can process the information necessary to correctly assess the movements of an economy influenced by the millions of decisions made by people around the world. As Hayek stated, the knowledge of the circumstances of time and place, held and acted upon by every individual in the world, make up an integral part of how the economy keeps moving.  “The continuous flow of goods and services is maintained by constant deliberate adjustments, by new dispositions made every day in the light of circumstances not known the day before, by B stepping in at once when A fails to deliver (Hayek).” The combination of aggregated information and the delayed effect of monetary policy on the economy can lead to undesirable outcomes. By the time macroeconomic metrics or models signal the need for sudden changes, it may be too late for monetary policy to make a difference.

There is another information problem on the other side of the equation. Because the Federal Reserve has so much power to influence the economy, there is an extreme focus on every communication that comes from the central bank. Not only are the press releases and minutes from the FOMC examined at the molecular level, every time a member of the FOMC says anything about monetary policy, the world is listening, and markets move. Financial markets are starving for information on what the Fed is going to do. Members of the FOMC are reluctant to be candid because anything they say can have a huge impact on financial markets. Despite efforts to make FOMC meetings and expectations for future interest rates more transparent, there is still a lot of ambiguity in what influences rate changes.

#Monetary Policy Frameworks

The current policy framework of inflation targeting stems directly from the Federal Reserve’s mandate to maintain stable prices. The main reasoning for using inflation targeting is that, “Most macroeconomists agree that, in the long run, the inflation rate is the only macroeconomic variable that monetary policy can affect (Bernanke).” Although inflation targeting provides a public signal of Federal Reserve policy, the process is still somewhat of a black box.  Inflation targeting gives the Federal Reserve latitude on how to achieve the target rate and how to respond to crisis situations. The Federal Reserve’s response to the recession that started in 2008 demonstrated the range of possible actions. This flexibility, while very useful when faced with a crisis, is a significant part of why communications on monetary policy are often murky. The FOMC tries to paint a general picture of the expected path rates will take through the dot plot and press releases. However, in the event of sudden changes, it is impossible for market participants to know how the federal reserve will react because there is no clear framework for what will influence policy. 

Hayek writes about how a price system can communicate vast amounts of information through a single number. Nominal GDP targeting is a type of rules-based policy that ties monetary policy to market expectations for nominal GDP through a price system. There is a nominal GDP futures market that acts as an information market for expectations of GDP. The Federal Reserve offers to buy and sell an unlimited number of contracts at a price of 1 + the target GDP growth rate. Market participants then vote with their dollars on what they think the actual GDP will be. The spot price of the contracts sends a signal to both market participants and the Federal Reserve about GDP expectations. It communicates to the Federal Reserve whether they need to expand or contract the money supply and at the same time communicates to market participants the likely policy response. This policy approach takes advantage of the knowledge of the circumstance of time and place that cannot be fed into a macroeconomic model and allows the “man on the spot” to contribute his knowledge to the information market (Hayek).

A nominal GDP futures market is a very effective way to communicate information about expectations of economic performance to both market participants and the Federal Reserve. However, this policy approach relies on the Federal Reserve’s ability to influence GDP through its monetary tools. One might expect that a growth in the money supply also causes a growth in aggregate demand. However, changes in the money supply may not have a causal effect on GDP growth, as is assumed by proponents of nominal GDP targeting. Research from the St. Louis Fed did find a correlation between growth of the money supply and increased GDP with a lag time of around 3 years. “At the 12-quarter horizon, for every 1 percent increase in money base growth, there is about 0.4 percent corresponding increase in GDP growth (Wen).” Research showing a strong causal relationship between changes in the money supply and changes in GDP must be found before the Federal Reserve adopts nominal GDP targeting as its policy approach. 

#Conclusion

So, what should central bankers do? Inflation targeting has proven an effective tool to maintain stable prices. However, the ambiguity of how policy decisions are made and inefficient communication of information to markets are significant disadvantages. The market-based nominal GDP targeting approach provides much clearer information on expectations of future monetary policy. The crucial question is if the Federal Reserve’s tools to change the money supply can also effectively influence GDP growth. If so, central bankers should adopt nominal GDP targeting as their policy approach. It is an effective way to maintain stable growth in the economy and clearly communicate information between market participants and central bankers.

<!--
# References
\setlength{\parindent}{-0.2in}
\setlength{\leftskip}{0.2in}
\setlength{\parskip}{8pt}
\vspace*{-0.2in}
\noindent
-->

